/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "../examples/rfc3280-PKIX1Implicit88.asn1"
 */

#include "AccessDescription.h"

static asn_TYPE_member_t asn_MBR_AccessDescription_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AccessDescription, accessMethod),
		(ASN_TAG_CLASS_UNIVERSAL | (6 << 2)),
		0,
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessMethod"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AccessDescription, accessLocation),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_GeneralName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessLocation"
		},
};
static ber_tlv_tag_t asn_DEF_AccessDescription_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_AccessDescription_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (6 << 2)), 0, 0, 0 }, /* accessMethod at 299 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* otherName at 156 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rfc822Name at 157 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* dNSName at 158 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* x400Address at 159 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 }, /* directoryName at 160 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 1, 0, 0 }, /* ediPartyName at 161 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 1, 0, 0 }, /* uniformResourceIdentifier at 162 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 1, 0, 0 }, /* iPAddress at 163 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 1, 0, 0 } /* registeredID at 164 */
};
static asn_SEQUENCE_specifics_t asn_SPC_AccessDescription_specs_1 = {
	sizeof(struct AccessDescription),
	offsetof(struct AccessDescription, _asn_ctx),
	asn_MAP_AccessDescription_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AccessDescription = {
	"AccessDescription",
	"AccessDescription",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AccessDescription_tags_1,
	sizeof(asn_DEF_AccessDescription_tags_1)
		/sizeof(asn_DEF_AccessDescription_tags_1[0]), /* 1 */
	asn_DEF_AccessDescription_tags_1,	/* Same as above */
	sizeof(asn_DEF_AccessDescription_tags_1)
		/sizeof(asn_DEF_AccessDescription_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AccessDescription_1,
	2,	/* Elements count */
	&asn_SPC_AccessDescription_specs_1	/* Additional specs */
};

