/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "../rfc3281-PKIXAttributeCertificate.asn1"
 */

#include "ACClearAttrs.h"

static asn_TYPE_member_t asn_MBR_attrs_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Attribute,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_attrs_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_attrs_specs_4 = {
	sizeof(struct attrs),
	offsetof(struct attrs, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_attrs_4 = {
	"attrs",
	"attrs",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_attrs_tags_4,
	sizeof(asn_DEF_attrs_tags_4)
		/sizeof(asn_DEF_attrs_tags_4[0]), /* 1 */
	asn_DEF_attrs_tags_4,	/* Same as above */
	sizeof(asn_DEF_attrs_tags_4)
		/sizeof(asn_DEF_attrs_tags_4[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_attrs_4,
	1,	/* Single element */
	&asn_SPC_attrs_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ACClearAttrs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ACClearAttrs, acIssuer),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_GeneralName,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"acIssuer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ACClearAttrs, acSerial),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"acSerial"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ACClearAttrs, attrs),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_attrs_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"attrs"
		},
};
static ber_tlv_tag_t asn_DEF_ACClearAttrs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ACClearAttrs_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, 0, 0 }, /* acSerial at 214 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* attrs at 216 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* otherName at 156 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* rfc822Name at 157 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* dNSName at 158 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 }, /* x400Address at 159 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 0, 0, 0 }, /* directoryName at 160 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 0, 0, 0 }, /* ediPartyName at 161 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 0, 0, 0 }, /* uniformResourceIdentifier at 162 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 0, 0, 0 }, /* iPAddress at 163 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 0, 0, 0 } /* registeredID at 164 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ACClearAttrs_specs_1 = {
	sizeof(struct ACClearAttrs),
	offsetof(struct ACClearAttrs, _asn_ctx),
	asn_MAP_ACClearAttrs_tag2el_1,
	11,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ACClearAttrs = {
	"ACClearAttrs",
	"ACClearAttrs",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ACClearAttrs_tags_1,
	sizeof(asn_DEF_ACClearAttrs_tags_1)
		/sizeof(asn_DEF_ACClearAttrs_tags_1[0]), /* 1 */
	asn_DEF_ACClearAttrs_tags_1,	/* Same as above */
	sizeof(asn_DEF_ACClearAttrs_tags_1)
		/sizeof(asn_DEF_ACClearAttrs_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ACClearAttrs_1,
	3,	/* Elements count */
	&asn_SPC_ACClearAttrs_specs_1	/* Additional specs */
};

