/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "AttributeCertificateVersion1"
 * 	found in "../rfc5652-AttributeCertificateVersion1.asn1"
 */

#include "AttributeCertificateV1.h"

static asn_TYPE_member_t asn_MBR_AttributeCertificateV1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateV1, acInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AttributeCertificateInfoV1,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"acInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateV1, signatureAlgorithm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlgorithmIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signatureAlgorithm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateV1, signature),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_BIT_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signature"
		},
};
static ber_tlv_tag_t asn_DEF_AttributeCertificateV1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_AttributeCertificateV1_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 2, 0, 0 }, /* signature at 45 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* acInfo at 43 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 0 } /* signatureAlgorithm at 44 */
};
static asn_SEQUENCE_specifics_t asn_SPC_AttributeCertificateV1_specs_1 = {
	sizeof(struct AttributeCertificateV1),
	offsetof(struct AttributeCertificateV1, _asn_ctx),
	asn_MAP_AttributeCertificateV1_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AttributeCertificateV1 = {
	"AttributeCertificateV1",
	"AttributeCertificateV1",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AttributeCertificateV1_tags_1,
	sizeof(asn_DEF_AttributeCertificateV1_tags_1)
		/sizeof(asn_DEF_AttributeCertificateV1_tags_1[0]), /* 1 */
	asn_DEF_AttributeCertificateV1_tags_1,	/* Same as above */
	sizeof(asn_DEF_AttributeCertificateV1_tags_1)
		/sizeof(asn_DEF_AttributeCertificateV1_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AttributeCertificateV1_1,
	3,	/* Elements count */
	&asn_SPC_AttributeCertificateV1_specs_1	/* Additional specs */
};

