/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "AttributeCertificateVersion1"
 * 	found in "../rfc5652-AttributeCertificateVersion1.asn1"
 */

#include "AttributeCertificateInfoV1.h"

static int asn_DFL_2_set_0(int set_value, void **sptr) {
	AttCertVersionV1_t *st = *sptr;
	
	if(!st) {
		if(!set_value) return -1;	/* Not a default value */
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	if(set_value) {
		/* Install default value 0 */
		return asn_long2INTEGER(st, 0);
	} else {
		/* Test default value 0 */
		long value;
		if(asn_INTEGER2long(st, &value))
			return -1;
		return (value == 0);
	}
}
static asn_TYPE_member_t asn_MBR_subject_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct subject, choice.baseCertificateID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_IssuerSerial,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"baseCertificateID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct subject, choice.subjectName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GeneralNames,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"subjectName"
		},
};
static asn_TYPE_tag2member_t asn_MAP_subject_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* baseCertificateID at 60 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* subjectName at 62 */
};
static asn_CHOICE_specifics_t asn_SPC_subject_specs_3 = {
	sizeof(struct subject),
	offsetof(struct subject, _asn_ctx),
	offsetof(struct subject, present),
	sizeof(((struct subject *)0)->present),
	asn_MAP_subject_tag2el_3,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_subject_3 = {
	"subject",
	"subject",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_subject_3,
	2,	/* Elements count */
	&asn_SPC_subject_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_attributes_10[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Attribute,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_attributes_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_attributes_specs_10 = {
	sizeof(struct attributesV1_t),
	offsetof(struct attributesV1_t, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_attributes_10 = {
	"attributes",
	"attributes",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_attributes_tags_10,
	sizeof(asn_DEF_attributes_tags_10)
		/sizeof(asn_DEF_attributes_tags_10[0]), /* 1 */
	asn_DEF_attributes_tags_10,	/* Same as above */
	sizeof(asn_DEF_attributes_tags_10)
		/sizeof(asn_DEF_attributes_tags_10[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_attributes_10,
	1,	/* Single element */
	&asn_SPC_attributes_specs_10	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_AttributeCertificateInfoV1_1[] = {
	{ ATF_POINTER, 1, offsetof(struct AttributeCertificateInfoV1, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_AttCertVersionV1,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		asn_DFL_2_set_0,	/* DEFAULT 0 */
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateInfoV1, subject),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_subject_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"subject"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateInfoV1, issuer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GeneralNames,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"issuer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateInfoV1, signature),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AlgorithmIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"signature"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateInfoV1, serialNumber),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_CertificateSerialNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"serialNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateInfoV1, attCertValidityPeriod),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_AttCertValidityPeriod,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"attCertValidityPeriod"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AttributeCertificateInfoV1, attributes),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_attributes_10,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"attributes"
		},
	{ ATF_POINTER, 2, offsetof(struct AttributeCertificateInfoV1, issuerUniqueID),
		(ASN_TAG_CLASS_UNIVERSAL | (3 << 2)),
		0,
		&asn_DEF_UniqueIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"issuerUniqueID"
		},
	{ ATF_POINTER, 1, offsetof(struct AttributeCertificateInfoV1, extensions),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Extensions,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extensions"
		},
};
static ber_tlv_tag_t asn_DEF_AttributeCertificateInfoV1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_AttributeCertificateInfoV1_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* version at 58 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, -1, 0 }, /* serialNumber at 66 */
    { (ASN_TAG_CLASS_UNIVERSAL | (3 << 2)), 7, 0, 0 }, /* issuerUniqueID at 69 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 4 }, /* issuer at 64 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -1, 3 }, /* signature at 65 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -2, 2 }, /* attCertValidityPeriod at 67 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 6, -3, 1 }, /* attributes at 68 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 8, -4, 0 }, /* extensions at 70 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* baseCertificateID at 60 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* subjectName at 62 */
};
static asn_SEQUENCE_specifics_t asn_SPC_AttributeCertificateInfoV1_specs_1 = {
	sizeof(struct AttributeCertificateInfoV1),
	offsetof(struct AttributeCertificateInfoV1, _asn_ctx),
	asn_MAP_AttributeCertificateInfoV1_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AttributeCertificateInfoV1 = {
	"AttributeCertificateInfoV1",
	"AttributeCertificateInfoV1",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AttributeCertificateInfoV1_tags_1,
	sizeof(asn_DEF_AttributeCertificateInfoV1_tags_1)
		/sizeof(asn_DEF_AttributeCertificateInfoV1_tags_1[0]), /* 1 */
	asn_DEF_AttributeCertificateInfoV1_tags_1,	/* Same as above */
	sizeof(asn_DEF_AttributeCertificateInfoV1_tags_1)
		/sizeof(asn_DEF_AttributeCertificateInfoV1_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AttributeCertificateInfoV1_1,
	9,	/* Elements count */
	&asn_SPC_AttributeCertificateInfoV1_specs_1	/* Additional specs */
};

