/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#include "AuthenticatedData.h"

static asn_TYPE_member_t asn_MBR_AuthenticatedData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticatedData, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_CMSVersion,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_POINTER, 1, offsetof(struct AuthenticatedData, originatorInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OriginatorInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"originatorInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticatedData, recipientInfos),
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_RecipientInfos,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recipientInfos"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticatedData, macAlgorithm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_MessageAuthenticationCodeAlgorithm,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"macAlgorithm"
		},
	{ ATF_POINTER, 1, offsetof(struct AuthenticatedData, digestAlgorithm),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DigestAlgorithmIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"digestAlgorithm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticatedData, encapContentInfo),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EncapsulatedContentInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"encapContentInfo"
		},
	{ ATF_POINTER, 1, offsetof(struct AuthenticatedData, authAttrs),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AuthAttributes,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"authAttrs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticatedData, mac),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_MessageAuthenticationCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mac"
		},
	{ ATF_POINTER, 1, offsetof(struct AuthenticatedData, unauthAttrs),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UnauthAttributes,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"unauthAttrs"
		},
};
static ber_tlv_tag_t asn_DEF_AuthenticatedData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_AuthenticatedData_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version at 223 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 7, 0, 0 }, /* mac at 230 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, 0, 1 }, /* macAlgorithm at 226 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -1, 0 }, /* encapContentInfo at 228 */
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 2, 0, 0 }, /* recipientInfos at 225 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* originatorInfo at 224 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 4, 0, 0 }, /* digestAlgorithm at 227 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 6, 0, 0 }, /* authAttrs at 229 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 8, 0, 0 } /* unauthAttrs at 231 */
};
static asn_SEQUENCE_specifics_t asn_SPC_AuthenticatedData_specs_1 = {
	sizeof(struct AuthenticatedData),
	offsetof(struct AuthenticatedData, _asn_ctx),
	asn_MAP_AuthenticatedData_tag2el_1,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_AuthenticatedData = {
	"AuthenticatedData",
	"AuthenticatedData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_AuthenticatedData_tags_1,
	sizeof(asn_DEF_AuthenticatedData_tags_1)
		/sizeof(asn_DEF_AuthenticatedData_tags_1[0]), /* 1 */
	asn_DEF_AuthenticatedData_tags_1,	/* Same as above */
	sizeof(asn_DEF_AuthenticatedData_tags_1)
		/sizeof(asn_DEF_AuthenticatedData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_AuthenticatedData_1,
	9,	/* Elements count */
	&asn_SPC_AuthenticatedData_specs_1	/* Additional specs */
};

