/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#include "CertificateChoices.h"

static asn_TYPE_member_t asn_MBR_CertificateChoices_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CertificateChoices, choice.certificate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Certificate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"certificate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertificateChoices, choice.extendedCertificate),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ExtendedCertificate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"extendedCertificate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertificateChoices, choice.v1AttrCert),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AttributeCertificateV1,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"v1AttrCert"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertificateChoices, choice.v2AttrCert),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AttributeCertificateV2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"v2AttrCert"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CertificateChoices, choice.other),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OtherCertificateFormat,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"other"
		},
};
static asn_TYPE_tag2member_t asn_MAP_CertificateChoices_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* certificate at 269 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* extendedCertificate at 270 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* v1AttrCert at 271 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 }, /* v2AttrCert at 272 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 4, 0, 0 } /* other at 273 */
};
static asn_CHOICE_specifics_t asn_SPC_CertificateChoices_specs_1 = {
	sizeof(struct CertificateChoices),
	offsetof(struct CertificateChoices, _asn_ctx),
	offsetof(struct CertificateChoices, present),
	sizeof(((struct CertificateChoices *)0)->present),
	asn_MAP_CertificateChoices_tag2el_1,
	5,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CertificateChoices = {
	"CertificateChoices",
	"CertificateChoices",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_CertificateChoices_1,
	5,	/* Elements count */
	&asn_SPC_CertificateChoices_specs_1	/* Additional specs */
};

