/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "../rfc3281-PKIXAttributeCertificate.asn1"
 */

#include "Clearance.h"

static asn_TYPE_member_t asn_MBR_securityCategories_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SecurityCategory,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_securityCategories_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_securityCategories_specs_4 = {
	sizeof(struct securityCategories),
	offsetof(struct securityCategories, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_securityCategories_4 = {
	"securityCategories",
	"securityCategories",
	SET_OF_free,
	SET_OF_print,
	SET_OF_constraint,
	SET_OF_decode_ber,
	SET_OF_encode_der,
	SET_OF_decode_xer,
	SET_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_securityCategories_tags_4,
	sizeof(asn_DEF_securityCategories_tags_4)
		/sizeof(asn_DEF_securityCategories_tags_4[0]) - 1, /* 1 */
	asn_DEF_securityCategories_tags_4,	/* Same as above */
	sizeof(asn_DEF_securityCategories_tags_4)
		/sizeof(asn_DEF_securityCategories_tags_4[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_securityCategories_4,
	1,	/* Single element */
	&asn_SPC_securityCategories_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Clearance_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Clearance, policyId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"policyId"
		},
	{ ATF_POINTER, 2, offsetof(struct Clearance, classList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ClassList,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"classList"
		},
	{ ATF_POINTER, 1, offsetof(struct Clearance, securityCategories),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_securityCategories_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"securityCategories"
		},
};
static ber_tlv_tag_t asn_DEF_Clearance_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Clearance_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* policyId at 177 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* classList at 178 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* securityCategories at 180 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Clearance_specs_1 = {
	sizeof(struct Clearance),
	offsetof(struct Clearance, _asn_ctx),
	asn_MAP_Clearance_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Clearance = {
	"Clearance",
	"Clearance",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Clearance_tags_1,
	sizeof(asn_DEF_Clearance_tags_1)
		/sizeof(asn_DEF_Clearance_tags_1[0]), /* 1 */
	asn_DEF_Clearance_tags_1,	/* Same as above */
	sizeof(asn_DEF_Clearance_tags_1)
		/sizeof(asn_DEF_Clearance_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Clearance_1,
	3,	/* Elements count */
	&asn_SPC_Clearance_specs_1	/* Additional specs */
};

