/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#include "ExtendedCertificateInfo.h"

static asn_TYPE_member_t asn_MBR_ExtendedCertificateInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ExtendedCertificateInfo, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_CMSVersion,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ExtendedCertificateInfo, certificate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Certificate,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"certificate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ExtendedCertificateInfo, attributes),
		(ASN_TAG_CLASS_UNIVERSAL | (17 << 2)),
		0,
		&asn_DEF_UnauthAttributes,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"attributes"
		},
};
static ber_tlv_tag_t asn_DEF_ExtendedCertificateInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ExtendedCertificateInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version at 362 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* certificate at 363 */
    { (ASN_TAG_CLASS_UNIVERSAL | (17 << 2)), 2, 0, 0 } /* attributes at 364 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ExtendedCertificateInfo_specs_1 = {
	sizeof(struct ExtendedCertificateInfo),
	offsetof(struct ExtendedCertificateInfo, _asn_ctx),
	asn_MAP_ExtendedCertificateInfo_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ExtendedCertificateInfo = {
	"ExtendedCertificateInfo",
	"ExtendedCertificateInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ExtendedCertificateInfo_tags_1,
	sizeof(asn_DEF_ExtendedCertificateInfo_tags_1)
		/sizeof(asn_DEF_ExtendedCertificateInfo_tags_1[0]), /* 1 */
	asn_DEF_ExtendedCertificateInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_ExtendedCertificateInfo_tags_1)
		/sizeof(asn_DEF_ExtendedCertificateInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ExtendedCertificateInfo_1,
	3,	/* Elements count */
	&asn_SPC_ExtendedCertificateInfo_specs_1	/* Additional specs */
};

