/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#include "PasswordRecipientInfo.h"

static asn_TYPE_member_t asn_MBR_PasswordRecipientInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PasswordRecipientInfo, version),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_CMSVersion,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"version"
		},
	{ ATF_POINTER, 1, offsetof(struct PasswordRecipientInfo, keyDerivationAlgorithm),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_KeyDerivationAlgorithmIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"keyDerivationAlgorithm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PasswordRecipientInfo, keyEncryptionAlgorithm),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_KeyEncryptionAlgorithmIdentifier,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"keyEncryptionAlgorithm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PasswordRecipientInfo, encryptedKey),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_EncryptedKey,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"encryptedKey"
		},
};
static ber_tlv_tag_t asn_DEF_PasswordRecipientInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_PasswordRecipientInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 0 }, /* version at 195 */
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, 0, 0 }, /* encryptedKey at 199 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 0 }, /* keyEncryptionAlgorithm at 198 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 } /* keyDerivationAlgorithm at 197 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PasswordRecipientInfo_specs_1 = {
	sizeof(struct PasswordRecipientInfo),
	offsetof(struct PasswordRecipientInfo, _asn_ctx),
	asn_MAP_PasswordRecipientInfo_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PasswordRecipientInfo = {
	"PasswordRecipientInfo",
	"PasswordRecipientInfo",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PasswordRecipientInfo_tags_1,
	sizeof(asn_DEF_PasswordRecipientInfo_tags_1)
		/sizeof(asn_DEF_PasswordRecipientInfo_tags_1[0]), /* 1 */
	asn_DEF_PasswordRecipientInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_PasswordRecipientInfo_tags_1)
		/sizeof(asn_DEF_PasswordRecipientInfo_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PasswordRecipientInfo_1,
	4,	/* Elements count */
	&asn_SPC_PasswordRecipientInfo_specs_1	/* Additional specs */
};

