/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "../rfc3281-PKIXAttributeCertificate.asn1"
 */

#include "V2Form.h"

static asn_TYPE_member_t asn_MBR_V2Form_1[] = {
	{ ATF_POINTER, 3, offsetof(struct V2Form, issuerName),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_GeneralNames,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"issuerName"
		},
	{ ATF_POINTER, 2, offsetof(struct V2Form, baseCertificateID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IssuerSerial,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"baseCertificateID"
		},
	{ ATF_POINTER, 1, offsetof(struct V2Form, objectDigestInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ObjectDigestInfo,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"objectDigestInfo"
		},
};
static ber_tlv_tag_t asn_DEF_V2Form_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_V2Form_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* issuerName at 116 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* baseCertificateID at 117 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 } /* objectDigestInfo at 118 */
};
static asn_SEQUENCE_specifics_t asn_SPC_V2Form_specs_1 = {
	sizeof(struct V2Form),
	offsetof(struct V2Form, _asn_ctx),
	asn_MAP_V2Form_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_V2Form = {
	"V2Form",
	"V2Form",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_V2Form_tags_1,
	sizeof(asn_DEF_V2Form_tags_1)
		/sizeof(asn_DEF_V2Form_tags_1[0]), /* 1 */
	asn_DEF_V2Form_tags_1,	/* Same as above */
	sizeof(asn_DEF_V2Form_tags_1)
		/sizeof(asn_DEF_V2Form_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_V2Form_1,
	3,	/* Elements count */
	&asn_SPC_V2Form_specs_1	/* Additional specs */
};

