/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "../rfc3281-PKIXAttributeCertificate.asn1"
 */

#ifndef	_AttributeCertificate_H_
#define	_AttributeCertificate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttributeCertificateInfo.h"
#include "AlgorithmIdentifier.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AttributeCertificate */
typedef struct AttributeCertificate {
	AttributeCertificateInfo_t	 acinfo;
	AlgorithmIdentifier_t	 signatureAlgorithm;
	BIT_STRING_t	 signatureValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AttributeCertificate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttributeCertificate;

#ifdef __cplusplus
}
#endif

#endif	/* _AttributeCertificate_H_ */
#include <asn_internal.h>
