/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_AttributeCertificateV2_H_
#define	_AttributeCertificateV2_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AttributeCertificate.h"

#ifdef __cplusplus
extern "C" {
#endif

/* AttributeCertificateV2 */
typedef AttributeCertificate_t	 AttributeCertificateV2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AttributeCertificateV2;
asn_struct_free_f AttributeCertificateV2_free;
asn_struct_print_f AttributeCertificateV2_print;
asn_constr_check_f AttributeCertificateV2_constraint;
ber_type_decoder_f AttributeCertificateV2_decode_ber;
der_type_encoder_f AttributeCertificateV2_encode_der;
xer_type_decoder_f AttributeCertificateV2_decode_xer;
xer_type_encoder_f AttributeCertificateV2_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _AttributeCertificateV2_H_ */
#include <asn_internal.h>
