/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_Countersignature_H_
#define	_Countersignature_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SignerInfo.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Countersignature */
typedef SignerInfo_t	 Countersignature_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Countersignature;
asn_struct_free_f Countersignature_free;
asn_struct_print_f Countersignature_print;
asn_constr_check_f Countersignature_constraint;
ber_type_decoder_f Countersignature_decode_ber;
der_type_encoder_f Countersignature_encode_der;
xer_type_decoder_f Countersignature_decode_xer;
xer_type_encoder_f Countersignature_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Countersignature_H_ */
#include <asn_internal.h>
