/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_EncryptedData_H_
#define	_EncryptedData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CMSVersion.h"
#include "EncryptedContentInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UnprotectedAttributes;

/* EncryptedData */
typedef struct EncryptedData {
	CMSVersion_t	 version;
	EncryptedContentInfo_t	 encryptedContentInfo;
	struct UnprotectedAttributes	*unprotectedAttrs	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EncryptedData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncryptedData;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UnprotectedAttributes.h"

#endif	/* _EncryptedData_H_ */
#include <asn_internal.h>
