/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_EncryptedContentInfo_H_
#define	_EncryptedContentInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ContentType.h"
#include "ContentEncryptionAlgorithmIdentifier.h"
#include "EncryptedContent.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EncryptedContentInfo */
typedef struct EncryptedContentInfo {
	ContentType_t	 contentType;
	ContentEncryptionAlgorithmIdentifier_t	 contentEncryptionAlgorithm;
	EncryptedContent_t	*encryptedContent	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EncryptedContentInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EncryptedContentInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _EncryptedContentInfo_H_ */
#include <asn_internal.h>
