/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_ExtendedCertificate_H_
#define	_ExtendedCertificate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ExtendedCertificateInfo.h"
#include "SignatureAlgorithmIdentifier.h"
#include "Signature.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExtendedCertificate */
typedef struct ExtendedCertificate {
	ExtendedCertificateInfo_t	 extendedCertificateInfo;
	SignatureAlgorithmIdentifier_t	 signatureAlgorithm;
	Signature_t	 signature;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExtendedCertificate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtendedCertificate;

#ifdef __cplusplus
}
#endif

#endif	/* _ExtendedCertificate_H_ */
#include <asn_internal.h>
