/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_ExtendedCertificateInfo_H_
#define	_ExtendedCertificateInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CMSVersion.h"
#include "Certificate.h"
#include "UnauthAttributes.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExtendedCertificateInfo */
typedef struct ExtendedCertificateInfo {
	CMSVersion_t	 version;
	Certificate_t	 certificate;
	UnauthAttributes_t	 attributes;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExtendedCertificateInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExtendedCertificateInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _ExtendedCertificateInfo_H_ */
#include <asn_internal.h>
