/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIXAttributeCertificate"
 * 	found in "../rfc3281-PKIXAttributeCertificate.asn1"
 */

#ifndef	_Holder_H_
#define	_Holder_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IssuerSerial;
struct GeneralNames;
struct ObjectDigestInfo;

/* Holder */
typedef struct Holder {
	struct IssuerSerial	*baseCertificateID	/* OPTIONAL */;
	struct GeneralNames	*entityName	/* OPTIONAL */;
	struct ObjectDigestInfo	*objectDigestInfo	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Holder_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Holder;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "IssuerSerial.h"
#include "GeneralNames.h"
#include "ObjectDigestInfo.h"

#endif	/* _Holder_H_ */
#include <asn_internal.h>
