/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_IssuerAndSerialNumber_H_
#define	_IssuerAndSerialNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Name.h"
#include "CertificateSerialNumber.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IssuerAndSerialNumber */
typedef struct IssuerAndSerialNumber {
	Name_t	 issuer;
	CertificateSerialNumber_t	 serialNumber;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IssuerAndSerialNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IssuerAndSerialNumber;

#ifdef __cplusplus
}
#endif

#endif	/* _IssuerAndSerialNumber_H_ */
#include <asn_internal.h>
