/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_KeyAgreeRecipientInfo_H_
#define	_KeyAgreeRecipientInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CMSVersion.h"
#include "OriginatorIdentifierOrKey.h"
#include "UserKeyingMaterial.h"
#include "KeyEncryptionAlgorithmIdentifier.h"
#include "RecipientEncryptedKeys.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* KeyAgreeRecipientInfo */
typedef struct KeyAgreeRecipientInfo {
	CMSVersion_t	 version;
	OriginatorIdentifierOrKey_t	 originator;
	UserKeyingMaterial_t	*ukm	/* OPTIONAL */;
	KeyEncryptionAlgorithmIdentifier_t	 keyEncryptionAlgorithm;
	RecipientEncryptedKeys_t	 recipientEncryptedKeys;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} KeyAgreeRecipientInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KeyAgreeRecipientInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _KeyAgreeRecipientInfo_H_ */
#include <asn_internal.h>
