/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_KeyTransRecipientInfo_H_
#define	_KeyTransRecipientInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CMSVersion.h"
#include "RecipientIdentifier.h"
#include "KeyEncryptionAlgorithmIdentifier.h"
#include "EncryptedKey.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* KeyTransRecipientInfo */
typedef struct KeyTransRecipientInfo {
	CMSVersion_t	 version;
	RecipientIdentifier_t	 rid;
	KeyEncryptionAlgorithmIdentifier_t	 keyEncryptionAlgorithm;
	EncryptedKey_t	 encryptedKey;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} KeyTransRecipientInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_KeyTransRecipientInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _KeyTransRecipientInfo_H_ */
#include <asn_internal.h>
