/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_OriginatorPublicKey_H_
#define	_OriginatorPublicKey_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AlgorithmIdentifier.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OriginatorPublicKey */
typedef struct OriginatorPublicKey {
	AlgorithmIdentifier_t	 algorithm;
	BIT_STRING_t	 publicKey;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OriginatorPublicKey_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OriginatorPublicKey;

#ifdef __cplusplus
}
#endif

#endif	/* _OriginatorPublicKey_H_ */
#include <asn_internal.h>
