/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_OriginatorInfo_H_
#define	_OriginatorInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CertificateSet;
struct RevocationInfoChoices;

/* OriginatorInfo */
typedef struct OriginatorInfo {
	struct CertificateSet	*certs	/* OPTIONAL */;
	struct RevocationInfoChoices	*crls	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OriginatorInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OriginatorInfo;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CertificateSet.h"
#include "RevocationInfoChoices.h"

#endif	/* _OriginatorInfo_H_ */
#include <asn_internal.h>
