/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_RecipientEncryptedKeys_H_
#define	_RecipientEncryptedKeys_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RecipientEncryptedKey;

/* RecipientEncryptedKeys */
typedef struct RecipientEncryptedKeys {
	A_SEQUENCE_OF(struct RecipientEncryptedKey) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RecipientEncryptedKeys_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RecipientEncryptedKeys;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RecipientEncryptedKey.h"

#endif	/* _RecipientEncryptedKeys_H_ */
#include <asn_internal.h>
