/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_RevocationInfoChoice_H_
#define	_RevocationInfoChoice_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CertificateList.h"
#include "OtherRevocationInfoFormat.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RevocationInfoChoice_PR {
	RevocationInfoChoice_PR_NOTHING,	/* No components present */
	RevocationInfoChoice_PR_crl,
	RevocationInfoChoice_PR_other
} RevocationInfoChoice_PR;

/* RevocationInfoChoice */
typedef struct RevocationInfoChoice {
	RevocationInfoChoice_PR present;
	union RevocationInfoChoice_u {
		CertificateList_t	 crl;
		OtherRevocationInfoFormat_t	 other;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RevocationInfoChoice_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RevocationInfoChoice;

#ifdef __cplusplus
}
#endif

#endif	/* _RevocationInfoChoice_H_ */
#include <asn_internal.h>
