/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_Signature_H_
#define	_Signature_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Signature */
typedef BIT_STRING_t	 Signature_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Signature;
asn_struct_free_f Signature_free;
asn_struct_print_f Signature_print;
asn_constr_check_f Signature_constraint;
ber_type_decoder_f Signature_decode_ber;
der_type_encoder_f Signature_encode_der;
xer_type_decoder_f Signature_decode_xer;
xer_type_encoder_f Signature_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Signature_H_ */
#include <asn_internal.h>
