/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "CryptographicMessageSyntax2004"
 * 	found in "../rfc5652-CryptographicMessageSyntax2004.asn1"
 */

#ifndef	_SignerIdentifier_H_
#define	_SignerIdentifier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IssuerAndSerialNumber.h"
#include "SubjectKeyIdentifier.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SignerIdentifier_PR {
	SignerIdentifier_PR_NOTHING,	/* No components present */
	SignerIdentifier_PR_issuerAndSerialNumber,
	SignerIdentifier_PR_subjectKeyIdentifier
} SignerIdentifier_PR;

/* SignerIdentifier */
typedef struct SignerIdentifier {
	SignerIdentifier_PR present;
	union SignerIdentifier_u {
		IssuerAndSerialNumber_t	 issuerAndSerialNumber;
		SubjectKeyIdentifier_t	 subjectKeyIdentifier;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignerIdentifier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignerIdentifier;

#ifdef __cplusplus
}
#endif

#endif	/* _SignerIdentifier_H_ */
#include <asn_internal.h>
